CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "WeatherData" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp with time zone NOT NULL,
    "Temperature" double precision NULL,
    "AirHumidity" double precision NULL,
    "Td" double precision NULL,
    "AtmPressure" double precision NULL,
    "AirDirection" text NULL,
    "AirSpeed" double precision NULL,
    "Cloudiness" double precision NULL,
    "H" double precision NULL,
    "VV" double precision NULL,
    "WeatherEvents" text NULL,
    CONSTRAINT "PK_WeatherData" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231117211118_Initial', '7.0.14');

COMMIT;

