// <auto-generated />
using System;
using DSWeatherMoscow.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DSWeatherMoscow.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20231117211118_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DSWeatherMoscow.Models.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirDirection")
                        .HasColumnType("text");

                    b.Property<double?>("AirHumidity")
                        .HasColumnType("double precision");

                    b.Property<double?>("AirSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("AtmPressure")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cloudiness")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("H")
                        .HasColumnType("double precision");

                    b.Property<double?>("Td")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("VV")
                        .HasColumnType("double precision");

                    b.Property<string>("WeatherEvents")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeatherData");
                });
#pragma warning restore 612, 618
        }
    }
}
